[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "serve-common"
version = "0"
requires-python = ">=3.10"

dependencies = [
	"falcon",
	"tomli ; python_version < '3.11'",
	"loguru",
	"inotify",
	"spectree",
	"pydantic"
]
